DemansAppWebPro/DemansAppWebPro/Controllers/U_AudioBooksController.cs
using DemansAppWebPro.Helper.DTO.AudioBooks;
using DemansAppWebPro.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Data;

namespace DemansAppWebPro.Controllers
{
    [Authorize(Roles = "User")]
    public class U_AudioBooksController : Controller
    {
        private readonly EntitiesContext db;

        public U_AudioBooksController(EntitiesContext _db)
        {
            db = _db;
        }
        public IActionResult Index(int id)
        {
            var userInfo = db.Users.Where(w => w.Id == id).FirstOrDefault();

            return View(userInfo);
        }

        [HttpPost]
        public JsonResult ShowAudioBooks(int userId)
        {
            try
            {
                //userId = 1002;
                Request.Form.TryGetValue("draw", out Microsoft.Extensions.Primitives.StringValues drawOut);

                var draw = drawOut.FirstOrDefault();

                Request.Form.TryGetValue("start", out Microsoft.Extensions.Primitives.StringValues startOut);
                var start = startOut.FirstOrDefault();

                Request.Form.TryGetValue("length", out Microsoft.Extensions.Primitives.StringValues lengthOut);
                var length = lengthOut.FirstOrDefault();

                Request.Form.TryGetValue("order[0][column]", out Microsoft.Extensions.Primitives.StringValues orderColumnOut);
                Request.Form.TryGetValue("columns[" + orderColumnOut.FirstOrDefault() + "][name]", out Microsoft.Extensions.Primitives.StringValues columnsNameOut);
                var sortColumn = columnsNameOut.FirstOrDefault();

                Request.Form.TryGetValue("order[0][dir]", out Microsoft.Extensions.Primitives.StringValues sortColumnDirOut);
                var sortColumnDir = sortColumnDirOut.FirstOrDefault();

                Request.Form.TryGetValue("search[value]", out Microsoft.Extensions.Primitives.StringValues searchValueOut);
                var searchValue = searchValueOut.FirstOrDefault() ?? "";

                //Paging Size 
                int pageSize = length != null ? Convert.ToInt32(length) : 0;
                int skip = start != null ? Convert.ToInt32(start) : 0;

                var showAudioBooksRequest = db.AudioBooks.Where(w => w.UserId == userId)
                  .Select(s => new showAudioBooksRequest()
                  {
                      Id = s.Id,
                      Name = s.Name,
                      Subject = s.Subject,
                      Text = s.Text,
                      Url = s.Url,

                  }).Skip(skip).Take(pageSize).ToList();
                if (!(string.IsNullOrEmpty(sortColumn) && string.IsNullOrEmpty(sortColumnDir)))
                {
                    switch (sortColumn)
                    {
                        case "Name":
                            if (sortColumnDir == "desc")
                                showAudioBooksRequest = (from o in showAudioBooksRequest orderby o.Name descending select o).ToList();
                            else
                                showAudioBooksRequest = (from o in showAudioBooksRequest orderby o.Name ascending select o).ToList();
                            break;
                        case "Subject":
                            if (sortColumnDir == "desc")
                                showAudioBooksRequest = (from o in showAudioBooksRequest orderby o.Subject descending select o).ToList();
                            else
                                showAudioBooksRequest = (from o in showAudioBooksRequest orderby o.Subject ascending select o).ToList();
                            break;
                        case "Id":
                            if (sortColumnDir == "desc")
                                showAudioBooksRequest = (from o in showAudioBooksRequest orderby o.Id descending select o).ToList();
                            else
                                showAudioBooksRequest = (from o in showAudioBooksRequest orderby o.Id ascending select o).ToList();
                            break;
                        default:
                            if (sortColumnDir == "desc")
                                showAudioBooksRequest = (from o in showAudioBooksRequest orderby o.Name descending select o).ToList();
                            else
                                showAudioBooksRequest = (from o in showAudioBooksRequest orderby o.Name ascending select o).ToList();
                            break;
                    }
                }
                var recordsTotal = db.AudioBooks.Where(w => w.UserId == userId).Count();

                return Json(new
                {
                    draw = draw,
                    recordsFiltered = recordsTotal,
                    recordsTotal = recordsTotal,
                    data = showAudioBooksRequest
                });
            }
            catch (Exception ex)
            {
                return Json(new { status = true, data = "", messages = ex.Message });
            }
        }

        [HttpPost]
        public JsonResult CheckAudioBook(int request)
        {
            try
            {
                var _c_audio_book = db.AudioBooks.Where(w => w.Id == request).FirstOrDefault();
                var _c_audio_book_list = db.AudioBooks.Where(w => w.Name == _c_audio_book.Name && w.Url == _c_audio_book.Url).Select(s => new { s.Status, s.Id }).ToList();

                for (var j = 0; j < _c_audio_book_list.Count(); j++)
                {
                    var _status = _c_audio_book_list[j].Status;
                    var _s_audio_book_id = _c_audio_book_list[j].Id;
                    var _s_audio_book = db.AudioBooks.Where(w => w.Id == _s_audio_book_id).FirstOrDefault();

                    if (_status == 1)
                    {
                        _s_audio_book.Status = 0;

                        db.AudioBooks.Update(_s_audio_book);
                        db.SaveChangesAsync();
                    }
                    else
                    {
                        _s_audio_book.Status = 1;

                        db.AudioBooks.Update(_s_audio_book);
                        db.SaveChangesAsync();
                    }
                }
                return Json(new { Status = true });
            }
            catch
            {
                return Json(new { Status = false });
            }
        }
    }
}

DemansAppWebPro/DemansAppWebPro/Views/U_AudioBooks/Index.cshtml
@model DemansAppWebPro.Models.Users
@{
    ViewData["UserId"] = Model.Id;
    ViewData["Title"] = "AudioBooks";
    Layout = "~/Views/Shared/_LayoutUser.cshtml";
}
@section css{
    <style type="text/css">
        .table_style {
            overflow: auto;
            max-width: 150px;
            text-align: center;
        }

        .table_style {
            text-align: center !important
        }

        div.dataTables_wrapper div.dataTables_length select {
            width: 50px !important;
        }

        div.dataTables_wrapper div.dataTables_length label {
            margin-left: 10px !important;
            margin-top: 13px !important;
        }

        div.dataTables_wrapper div.dataTables_info {
            margin-left: 10px !important;
        }

        div.dataTables_wrapper div.dataTables_filter input {
            margin-right: 10px !important;
            margin-top: 13px !important;
        }

        .dataTables_wrapper .dataTables_paginate .paginate_button {
            padding: 2px !important
        }

        div.dataTables_wrapper div.dataTables_paginate {
            margin-right: 10px !important
        }

        .modal-input-style {
            margin-left: 10px !important;
        }

        .modal-label-style {
            padding-left: 20px !important;
        }

        @@media (min-width: 1400px) {
            .container, .container-sm, .container-md, .container-lg, .container-xl, .container-xxl {
                max-width: 1450px;
            }
        }

        .container {
            padding-top: 40px !important;
        }
    </style>
}

<div class="container">
    <div class="row">

        <div class="card">
            <div class="card-header">
                <h4 class="card-title">Sesli Kitaplar</h4>
            </div><!--end card-header-->
            <div class="card-body">
                <div class="card">
                    <div class="table-responsive">
                        <table id="audio_book_table" class="table table-striped table-bordered dt-responsive nowrap" style="vertical-align:middle; width:100%;">
                            <thead>
                                <tr>
                                    <th class="table-style">Ad</th>
                                    <th class="table-style">Konusu</th>
                                    <th class="table-style">Text</th>
                                    <th class="table-style">Url</th>
                                    <th class="table-style">Durumu</th>
                                </tr>
                            </thead>
                        </table>
                    </div>
                </div>
            </div><!--end card-body-->
        </div><!--end card-->


    </div>
</div>

@*<div class="card">
    <div class="card-header">
        <div class="row text-center">
            <h3 class="page-title col-sm-10">Sesli Kitaplar</h3>
        </div>
    </div>
</div>
<div class="card">
    <div class="table-responsive">
        <table id="audio_book_table" class="table table-striped table-bordered dt-responsive nowrap" style="vertical-align:middle; width:100%;">
            <thead>
                <tr>
                    <th class="table-style">Ad</th>
                    <th class="table-style">Konusu</th>
                    <th class="table-style">Text</th>
                    <th class="table-style">Url</th>
                    <th class="table-style">Durumu</th>
                </tr>
            </thead>
        </table>
    </div>
</div>
<div class="card-body">
</div><!--end AudioBooks Table-->*@



@section scripts {

    <script type="text/javascript">

        var audioBookTablo = null;
        $((_$) => {
            showAudioBooks();
        });

        var showAudioBooks = () => {
            if (audioBookTablo == null)
                audioBookTablo = $('#audio_book_table').DataTable({
                    language: { url: '../dil.json' },
                    processing: true,
                    serverSide: true,
                    paging: true,
                    filter: true,
                    scrollCollapse: true,
                    orderMulti: true,
                    order: [[1, "asc"]],
                    ajax: {
                        url: '@Url.Action("ShowAudioBooks", "U_AudioBooks")',
                        type: "POST",
                        datatype: "json",
                        data: function(d){
                            d.userId = @Model.Id;
                        }
                    },
                    createdRow: function (row, data, dataIndex) {
                    },
                    columnDefs: [{ "defaultContent": "-", "targets": "_all" }],
                    columns: [
                        {
                            "className": "table_style",
                            "render": (data, type, row) => {
                                console.log(row);
                                return row.name;
                            }, "name": "name",
                        },
                        {
                            "className": "table_style",
                            "render": (data, type, row) => {
                                return row.subject;
                            }, "name": "subject"
                        },
                        {
                            "className": "table_style",
                            "render": (data, type, row) => {
                                return row.text;
                            }, "name": "text"
                        },
                        {
                            "className": "table_style",
                            "render": (data, type, row) => {
                                return row.url;
                            }, "name": "url"
                        },

                        //Sesli Kitap Durum
                        {
                            "className": "table_style",
                            "render": function (data, type, row) {
                                let check = row.status == 1 ? 'checked' : 'nchecked';
                                return `<div class="form-check form-switch form-switch-warning" style="pading-left:70px;">
                                                                        <input class="form-check-input" type="checkbox" id="checked_${row.id}" onclick="javascript: checkAudioBook(${row.id})" ${check}>
                                                                </div>`;
                            }, "name": "status"
                        },
                    ],
                    fixedColumns: true,
                    scrollCollapse: true,
                    initComplete: function (settings, json) {
                        $('#audio_book_table_filter input').unbind();
                        $('#audio_book_table_filter input').bind('keyup', function (e) {
                            if (e.keyCode == 13) {
                                audioBookTablo.search(this.value).draw();
                            }
                        });

                        $('.dataTables_scrollBody').removeAttr('style').css({
                            'position': 'relative',
                            'overflow-y': 'auto',
                            'overflow-x': 'auto',
                            'width': '100%',
                            'max-height': ((window.innerHeight / 2) + 120) + 'px'
                        });

                    }

                })
        }

        var checkAudioBook = (checkId) => {
            $.post('@Url.Action("CheckAudioBook","U_AudioBooks")', { request: checkId }, (d, s) => {

                if (s == 'success') {
                    if (audioBookTablo != null)
                        audioBookTablo.ajax.reload();

                    const Toast = Swal.mixin({
                        toast: true,
                        position: 'top-end',
                        showConfirmButton: false,
                        timer: 3000,
                        timerProgressBar: true,
                        didOpen: (toast) => {
                            toast.addEventListener('mouseenter', Swal.stopTimer)
                            toast.addEventListener('mouseleave', Swal.resumeTimer)
                        }
                    })

                    Toast.fire({
                        icon: 'success',
                        title: 'Durum değiştirildi.'
                    })
                }
                else {
                    const Toast = Swal.mixin({
                        toast: true,
                        position: 'top-end',
                        showConfirmButton: false,
                        timer: 3000,
                        timerProgressBar: true,
                        didOpen: (toast) => {
                            toast.addEventListener('mouseenter', Swal.stopTimer)
                            toast.addEventListener('mouseleave', Swal.resumeTimer)
                        }
                    })

                    Toast.fire({
                        icon: 'success',
                        title: 'Durum değiştirilemedi.'
                    })
                }
            });
        }
    </script>
    }