DemansAppWebPro/DemansAppWebPro/Controllers/U_CompanionDetailsController.cs
using DemansAppWebPro.Helper.DTO.Companions;
using DemansAppWebPro.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Data;

namespace DemansAppWebPro.Controllers
{
    [Authorize(Roles = "User")]
    public class U_CompanionDetailsController : Controller
    {
        private readonly EntitiesContext db;

        public U_CompanionDetailsController(EntitiesContext _db)
        {
            db = _db;
        }
        public IActionResult Index(int id)
        {
            var userInfo = db.Users.Where(w => w.Id == id).FirstOrDefault();

            return View(userInfo);
        }
        [HttpPost]
        public JsonResult ShowCompanion(int userId)
        {
            try
            {
                var _companion = db.Companions.Where(w => w.UserId == userId).FirstOrDefault();
                if(_companion == null) { return Json(new { status = false, msg = "Refakatçı Bilgisine Ulaşılamadı." }); }

                return Json(new { status = true, data =  _companion }); 
            }
            catch (Exception ex)
            {
                return Json(new {status = false, msg = ex.Message});
            }
        }

        [HttpPost]
        public JsonResult AddCompanion(addCompanionsRequest request)
        {
            try
            {
                var _c = db.Companions.Where(w => w.UserId == request.UserId).FirstOrDefault();
                if(_c == null)
                {
                    var _companions = new Companions()
                    {
                        Name = request.Name,
                        Surname = request.Surname,
                        Adress = request.Adress,
                        Email = request.Email,
                        Sex = request.Sex,
                        Phone = request.Phone,
                        UserId = request.UserId,
                        Status = 1
                    };
                    db.Companions.Add(_companions);
                    db.SaveChanges();
                }
                else
                {
                    _c.Name = request.Name;
                    _c.Surname = request.Surname;
                    _c.Adress = request.Adress;
                    _c.Email = request.Email;
                    _c.Sex = request.Sex;
                    _c.Phone = request.Phone;

                    db.Companions.Update(_c);
                    db.SaveChanges();
                }

                return Json(new { Status = true, Messages = "Refakatçı başarıyla güncellendi." });
            }
            catch (Exception ex)
            {
                return Json(new { Status = false, data = "", Messages = ex.Message });
            }
        }
    }
}

DemansAppWebPro/DemansAppWebPro/Views/U_CompanionDetails/Index.cshtml
@model DemansAppWebPro.Models.Users
@{
    ViewData["UserId"] = Model.Id;
    ViewData["Title"] = "ProfileDetails Page";
    Layout = "~/Views/Shared/_LayoutUser.cshtml";
}

@section css{
    <style type="text/css">
        .button-style {
            background-color: #ED5E31 !important;
            border-color: #ED5E31 !important;
        }

        .dbutton-style {
            background-color: white !important;
            color: #ED5E31 !important;
        }

        @@media (min-width: 1400px) {
            .container, .container-sm, .container-md, .container-lg, .container-xl, .container-xxl {
                max-width: 1450px;
            }
        }

        .container {
            padding-top: 40px !important;
        }

        .form-control, .form-select {
            width: 75% !important;
        }

        .parsley-equalto {
            margin-left: 200px !important;
        }
    </style>
}
<div class="container">
    <div class="card">
        <div class="card-header">
            <h4 class="card-title"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Hasta Yakını Profil Detay</font></font></h4>
            <p class="text-muted mb-0"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Hasta yakını profilini oluşturun.</font></font></p>
        </div><!--end card-header-->
        <div class="card-body">
            <form>
                <div class="mb-3 row">
                    <label for="example-text-input" class="col-sm-2 form-label align-self-center mb-lg-0 text-end"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Adı</font></font></label>
                    <div class="col-sm-10">
                        <input class="form-control" type="text" placeholder="Ad" id="name">
                    </div>
                </div>
                <div class="mb-3 row">
                    <label for="example-text-input" class="col-sm-2 form-label align-self-center mb-lg-0 text-end"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Soyadı</font></font></label>
                    <div class="col-sm-10">
                        <input class="form-control" type="text" placeholder="Soyad" id="surname">
                    </div>
                </div>
                <div class="mb-3 row">
                    <label class="col-sm-2 form-label align-self-center mb-lg-0 text-end"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Cinsiyet</font></font></label>
                    <div class="col-sm-10">
                        <select class="form-select" aria-label="Varsayılan seçim örneği">
                            <option selected=""><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Seçiniz</font></font></option>
                            <option id="women" value="1"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Kadın</font></font></option>
                            <option id="men" value="2"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Erkek</font></font></option>
                        </select>
                    </div>
                </div>
                <div class="mb-3 row">
                    <label for="example-tel-input" class="col-sm-2 form-label align-self-center mb-lg-0 text-end"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Telefon</font></font></label>
                    <div class="col-sm-10">
                        <input class="form-control" type="tel" placeholder="(XXX) XXX XX XX" id="phone">
                    </div>
                </div>
                <div class="mb-3 row">
                    <label for="example-email-input" class="col-sm-2 form-label align-self-center mb-lg-0 text-end"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">E-mail</font></font></label>
                    <div class="col-sm-10">
                        <input class="form-control" type="email" placeholder="email@email.com" id="email">
                    </div>
                </div>

                <div class="mb-3 row">
                    <label for="example-text-input" class="col-sm-2 form-label align-self-center mb-lg-0 text-end"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Kısa Adres</font></font></label>
                    <div class="col-sm-10">
                        <input class="form-control" type="text" id="address">
                    </div>
                </div>

                <div style="margin-left:183px !important;">
                    <button type="button" class="btn btn-primary button-style" onclick="javascript: addCompanion();"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Değişiklikleri Kaydet</font></font></button>
                    <button type="button" class="btn btn-danger dbutton-style" onclick="javascript: reloadPage();"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Değişikliklerden vazgeç</font></font></button>
                </div>

            </form>
        </div><!--end card-body-->
    </div>
</div>



@section scripts {

    <script type="text/javascript">


        $((_$) => {
            showCompanion();
        });

        var reloadPage = () => {
            location.reload();
        };

        var showCompanion = () => {
            $.post('@Url.Action("ShowCompanion","U_CompanionDetails")', { userId: @Model.Id }, (d, s) => {
                console.log(d);
                document.getElementById('name').value = d.data.Name;
                document.getElementById('surname').value = d.data.Surname;
                document.getElementById('phone').value = d.data.Phone;
                document.getElementById('email').value = d.data.Email;
                document.getElementById('address').value = d.data.Adress;
                if (d.data.Sex == true) {
                    $("#women").prop("selected", true);
                } else {
                    $("#men").prop("selected", true);
                }
            })
        }

        var addCompanion = () => {
            var CompanionNameControl = document.getElementById('name').value ;
            var CompanionSurnameControl = document.getElementById('surname').value;
            var AddressControl = document.getElementById('phone').value ;
            var EpostaControl = document.getElementById('email').value ;
            var PhoneControl = document.getElementById('address').value;
            var SexControl = true;
            if (document.getElementById('women').checked == true) {
                SexControl = true;
                console.log("true" + SexControl);
            }
            else {
                SexControl = false;
                console.log("false" + SexControl);

            }

            if ( !CompanionNameControl || !CompanionSurnameControl || !AddressControl || !EpostaControl || !PhoneControl) {
                Command: toastr["warning"]("Lütfen Kullanıcı / Refakatçi Adı / Refakatçi Soyadı / Adres / Email / Telefon bilgisini giriniz.", "Ekleme başarısız!")
                toastr.options = {
                    "closeButton": true,
                    "debug": false,
                    "newestOnTop": false,
                    "progressBar": false,
                    "positionClass": "toast-top-right",
                    "preventDuplicates": false,
                    "onclick": null,
                    "showDuration": "300",
                    "hideDuration": "1000",
                    "timeOut": "8000",
                    "extendedTimeOut": "1000",
                    "showEasing": "swing",
                    "hideEasing": "linear",
                    "showMethod": "fadeIn",
                    "hideMethod": "fadeOut"
                }
              
            }else{
                console.log("else");
                var formData = new FormData();
                formData.append('UserId', @Model.Id);
                formData.append('Name', CompanionNameControl);
                formData.append('Surname', CompanionSurnameControl);
                formData.append('Adress', AddressControl);
                formData.append('Email', EpostaControl);
                formData.append('Phone', PhoneControl);
                formData.append('Sex', SexControl);

                $.ajax({
                    type: 'POST',
                    url: '@Url.Action("AddCompanion","U_CompanionDetails")',
                    data: formData,
                    async: true,
                    contentType: false,
                    processData: false,
                    success: data => {

                        if (data.Status == true) {

                            Command: toastr["success"]("Ekleme işlemi başarıyla gerçekleşti.")

                            toastr.options = {
                                "closeButton": false,
                                "debug": false,
                                "newestOnTop": false,
                                "progressBar": false,
                                "positionClass": "toast-top-right",
                                "preventDuplicates": false,
                                "onclick": null,
                                "showDuration": "300",
                                "hideDuration": "1000",
                                "timeOut": "8000",
                                "extendedTimeOut": "1000",
                                "showEasing": "swing",
                                "hideEasing": "linear",
                                "showMethod": "fadeIn",
                                "hideMethod": "fadeOut"
                            }
                            reloadPage();

                        }
                        else {
                            Command: toastr["error"]("Ekleme işlemi gerçekleşemedi.'")

                            toastr.options = {
                                "closeButton": false,
                                "debug": false,
                                "newestOnTop": false,
                                "progressBar": false,
                                "positionClass": "toast-top-right",
                                "preventDuplicates": false,
                                "onclick": null,
                                "showDuration": "300",
                                "hideDuration": "1000",
                                "timeOut": "8000",
                                "extendedTimeOut": "1000",
                                "showEasing": "swing",
                                "hideEasing": "linear",
                                "showMethod": "fadeIn",
                                "hideMethod": "fadeOut"
                            }
                        }
                    },
                });
            }

            
        }
    </script>
    }